INSERT INTO Destinos (destino, nombre) VALUES (1, 'Puntarenas');
INSERT INTO Destinos (destino, nombre) VALUES (2, 'Jambi');
INSERT INTO Destinos (destino, nombre) VALUES (3, 'Puntarenas');
INSERT INTO Destinos (destino, nombre) VALUES (4, 'Biobío');
INSERT INTO Destinos (destino, nombre) VALUES (5, 'Azad Kashmir');
INSERT INTO Destinos (destino, nombre) VALUES (6, 'North Island');
INSERT INTO Destinos (destino, nombre) VALUES (7, 'Mexico City');
INSERT INTO Destinos (destino, nombre) VALUES (8, 'Dalarnas län');
INSERT INTO Destinos (destino, nombre) VALUES (9, 'Huádōng');
INSERT INTO Destinos (destino, nombre) VALUES (10, 'Lima');
INSERT INTO Destinos (destino, nombre) VALUES (11, 'İzmir');
INSERT INTO Destinos (destino, nombre) VALUES (12, 'Huádōng');
INSERT INTO Destinos (destino, nombre) VALUES (13, 'Tyrol');
INSERT INTO Destinos (destino, nombre) VALUES (14, 'Punjab');
INSERT INTO Destinos (destino, nombre) VALUES (15, 'Antalya');
INSERT INTO Destinos (destino, nombre) VALUES (16, 'Baja California');
INSERT INTO Destinos (destino, nombre) VALUES (17, 'South Gyeongsang');
INSERT INTO Destinos (destino, nombre) VALUES (18, 'São Paulo');
INSERT INTO Destinos (destino, nombre) VALUES (19, 'Córdoba');
INSERT INTO Destinos (destino, nombre) VALUES (20, 'Cartago');
INSERT INTO Destinos (destino, nombre) VALUES (21, 'Ninh Bình');
INSERT INTO Destinos (destino, nombre) VALUES (22, 'O\'Higgins');
INSERT INTO Destinos (destino, nombre) VALUES (23, 'Friuli-Venezia Giulia');
INSERT INTO Destinos (destino, nombre) VALUES (24, 'Lambayeque');
INSERT INTO Destinos (destino, nombre) VALUES (25, 'Berkshire');
INSERT INTO Destinos (destino, nombre) VALUES (26, 'Selkirkshire');
INSERT INTO Destinos (destino, nombre) VALUES (27, 'Khyber Pakhtoonkhwa');
INSERT INTO Destinos (destino, nombre) VALUES (28, 'Kostroma Oblast');
INSERT INTO Destinos (destino, nombre) VALUES (29, 'Madrid');
INSERT INTO Destinos (destino, nombre) VALUES (30, 'La Libertad');
INSERT INTO Destinos (destino, nombre) VALUES (31, 'Comunitat Valenciana');
INSERT INTO Destinos (destino, nombre) VALUES (32, 'Munster');
INSERT INTO Destinos (destino, nombre) VALUES (33, 'Basilicata');
INSERT INTO Destinos (destino, nombre) VALUES (34, 'Tarapacá');
INSERT INTO Destinos (destino, nombre) VALUES (35, 'Leinster');
INSERT INTO Destinos (destino, nombre) VALUES (36, 'Xīnán');
INSERT INTO Destinos (destino, nombre) VALUES (37, 'Newfoundland and Labrador');
INSERT INTO Destinos (destino, nombre) VALUES (38, 'Santander');
INSERT INTO Destinos (destino, nombre) VALUES (39, 'Southeast Sulawesi');
INSERT INTO Destinos (destino, nombre) VALUES (40, 'Jönköpings län');
INSERT INTO Destinos (destino, nombre) VALUES (41, 'Oklahoma');
INSERT INTO Destinos (destino, nombre) VALUES (42, 'Magdalena');
INSERT INTO Destinos (destino, nombre) VALUES (43, 'Maranhão');
INSERT INTO Destinos (destino, nombre) VALUES (44, 'Friuli-Venezia Giulia');
INSERT INTO Destinos (destino, nombre) VALUES (45, 'İzmir');
INSERT INTO Destinos (destino, nombre) VALUES (46, 'Cajamarca');
INSERT INTO Destinos (destino, nombre) VALUES (47, 'Bayern');
INSERT INTO Destinos (destino, nombre) VALUES (48, 'Connacht');
INSERT INTO Destinos (destino, nombre) VALUES (49, 'Oaxaca');
INSERT INTO Destinos (destino, nombre) VALUES (50, 'Gävleborgs län');
INSERT INTO Destinos (destino, nombre) VALUES (51, 'Minas Gerais');
INSERT INTO Destinos (destino, nombre) VALUES (52, 'Wielkopolskie');
INSERT INTO Destinos (destino, nombre) VALUES (53, 'Hà Nội');
INSERT INTO Destinos (destino, nombre) VALUES (54, 'Vermont');
INSERT INTO Destinos (destino, nombre) VALUES (55, 'Australian Capital Territory');
INSERT INTO Destinos (destino, nombre) VALUES (56, 'Styria');
INSERT INTO Destinos (destino, nombre) VALUES (57, 'FATA');
INSERT INTO Destinos (destino, nombre) VALUES (58, 'Vlaams-Brabant');
INSERT INTO Destinos (destino, nombre) VALUES (59, 'New Brunswick');
INSERT INTO Destinos (destino, nombre) VALUES (60, 'Jönköpings län');
INSERT INTO Destinos (destino, nombre) VALUES (61, 'Norte de Santander');
INSERT INTO Destinos (destino, nombre) VALUES (62, 'Pennsylvania');
INSERT INTO Destinos (destino, nombre) VALUES (63, 'Namen');
INSERT INTO Destinos (destino, nombre) VALUES (64, 'Nordrhein-Westphalen');
INSERT INTO Destinos (destino, nombre) VALUES (65, 'North Island');
INSERT INTO Destinos (destino, nombre) VALUES (66, 'North Sulawesi');
INSERT INTO Destinos (destino, nombre) VALUES (67, 'Namen');
INSERT INTO Destinos (destino, nombre) VALUES (68, 'Bayern');
INSERT INTO Destinos (destino, nombre) VALUES (69, 'Veneto');
INSERT INTO Destinos (destino, nombre) VALUES (70, 'Arizona');
INSERT INTO Destinos (destino, nombre) VALUES (71, 'Gangwon');
INSERT INTO Destinos (destino, nombre) VALUES (72, 'Quebec');
INSERT INTO Destinos (destino, nombre) VALUES (73, 'Piura');
INSERT INTO Destinos (destino, nombre) VALUES (74, 'San Andrés y Providencia');
INSERT INTO Destinos (destino, nombre) VALUES (75, 'Madrid');
INSERT INTO Destinos (destino, nombre) VALUES (76, 'Huádōng');
INSERT INTO Destinos (destino, nombre) VALUES (77, 'Vorarlberg');
INSERT INTO Destinos (destino, nombre) VALUES (78, 'Xīběi');
INSERT INTO Destinos (destino, nombre) VALUES (79, 'Goiás');
INSERT INTO Destinos (destino, nombre) VALUES (80, 'Morelos');
INSERT INTO Destinos (destino, nombre) VALUES (81, 'Northern Territory');
INSERT INTO Destinos (destino, nombre) VALUES (82, 'South Australia');
INSERT INTO Destinos (destino, nombre) VALUES (83, 'Friesland');
INSERT INTO Destinos (destino, nombre) VALUES (84, 'Manisa');
INSERT INTO Destinos (destino, nombre) VALUES (85, 'Nevada');
INSERT INTO Destinos (destino, nombre) VALUES (86, 'South Jeolla');
INSERT INTO Destinos (destino, nombre) VALUES (87, 'Buteshire');
INSERT INTO Destinos (destino, nombre) VALUES (88, 'Punjab');
INSERT INTO Destinos (destino, nombre) VALUES (89, 'Brussels Hoofdstedelijk Gewest');
INSERT INTO Destinos (destino, nombre) VALUES (90, 'Luxemburg');
INSERT INTO Destinos (destino, nombre) VALUES (91, 'Puntarenas');
INSERT INTO Destinos (destino, nombre) VALUES (92, 'Vlaams-Brabant');
INSERT INTO Destinos (destino, nombre) VALUES (93, 'Uttar Pradesh');
INSERT INTO Destinos (destino, nombre) VALUES (94, 'Riau');
INSERT INTO Destinos (destino, nombre) VALUES (95, 'Bình Phước');
INSERT INTO Destinos (destino, nombre) VALUES (96, 'Nuevo León');
INSERT INTO Destinos (destino, nombre) VALUES (97, 'Carinthia');
INSERT INTO Destinos (destino, nombre) VALUES (98, 'New South Wales');
INSERT INTO Destinos (destino, nombre) VALUES (99, 'Nariño');
INSERT INTO Destinos (destino, nombre) VALUES (100, 'Sardegna');
